(setq auto-mode-alist (cons (cons "\\.tex$" 'yatex-mode) auto-mode-alist))
(autoload 'yatex-mode "yatex" "Yet Another LaTeX mode" t)
(setq YaTeX-inhibit-prefix-letter nil)
;; (setq YaTeX-kanji-code 3)
(setq YaTeX-kanji-code nil)
(setq dvi2-command "xdvi-ja")
(setq tex-command "latexmk -pvc")
(setq YaTeX-use-LaTeX2e t)
;; (setq bibtex-command "pbibtex")
;; (setq tex-command "platex -interaction=nonstopmode -kanji=utf8")
